spring.application.name=customization-platform
server.port=8080
file.paths.users=src/main/resources/data/users.txt
file.paths.packages=src/main/resources/data/packages.txt
file.paths.bookings=src/main/resources/data/bookings.txt
file.paths.admins=src/main/resources/data/admins.txt
file.paths.reviews=src/main/resources/data/reviews.txt
logging.level.com.tourism=DEBUG